name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install -e .[dev]
      - name: Install helper package
        run: pip install -e binja_helpers/binja_helpers
      - name: Run Ruff
        run: ruff check
      - name: Run Mypy and Flake8
        run: bash run_mypy.sh
      - name: Run Pytest with coverage
        run: pytest --cov=src --cov-report=xml --cov-report=term
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
