name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install -e .[dev]
      - name: Download demo data
        run: |
          curl -L -o DOTTDEMO.ZIP https://archive.org/download/DayOfTheTentacleDemo/DOTTDEMO.ZIP || true
          if [ -f DOTTDEMO.ZIP ]; then
            unzip -q DOTTDEMO.ZIP
            python converter/cli.py DOTTDEMO.000 DOTTDEMO.001 -o DOTTDEMO.bsc6
          fi
      - name: Run Ruff
        run: ruff check
      - name: Run Mypy and Flake8
        run: bash run_mypy.sh
      - name: Run Pytest with coverage
        run: pytest --cov=src --cov-report=xml --cov-report=term
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
